

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 .\\woman_tall_unw.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('https://res.cloudinary.com/dfzxz7xsy/image/upload/v1687142745/Avatar/woman_tall_nrw_atmyll_gpxwn7.glb');
  return (
    <group {...props} dispose={null} scale={0.01}>
      <primitive object={nodes.pelvis} />
      <primitive object={nodes.neutral_bone} />
      {/* <skinnedMesh geometry={nodes.Component_Pant.geometry} material={materials['Wolf3D_Outfit_Bottom.001']} skeleton={nodes.Component_Pant.skeleton} />
      <skinnedMesh geometry={nodes.Component_Shirt.geometry} material={materials['Wolf3D_Outfit_Top.001']} skeleton={nodes.Component_Shirt.skeleton} />
      <skinnedMesh geometry={nodes.Component_Shoe.geometry} material={materials['Wolf3D_Outfit_Footwear.001']} skeleton={nodes.Component_Shoe.skeleton} /> */}
      <skinnedMesh castShadow geometry={nodes.f_tal_nrw_body_preview.geometry} material={materials['Fbx Default Material 0']} skeleton={nodes.f_tal_nrw_body_preview.skeleton} />
      <skinnedMesh castShadow geometry={nodes.Glass.geometry} material={materials.Wolf3D_Glasses} skeleton={nodes.Glass.skeleton} />
      <skinnedMesh castShadow geometry={nodes.Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Hair.skeleton} />
      <skinnedMesh castShadow name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <skinnedMesh castShadow name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <skinnedMesh castShadow name="Head" geometry={nodes.Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Head.skeleton} morphTargetDictionary={nodes.Head.morphTargetDictionary} morphTargetInfluences={nodes.Head.morphTargetInfluences} />
    </group>
    
  )
}

useGLTF.preload('https://res.cloudinary.com/dfzxz7xsy/image/upload/v1687142745/Avatar/woman_tall_nrw_atmyll_gpxwn7.glb')




















// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function Model({ ...props }) {
//   const group = useRef();
//   const { nodes, materials } = useGLTF(
//     "https://res.cloudinary.com/dfzxz7xsy/image/upload/v1686924635/GLB%20Folder/test_esqu05.glb"
//   );
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <primitive object={nodes.Hips} />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Body.geometry}
//         material={materials.Wolf3D_Body}
//         skeleton={nodes.Wolf3D_Body.skeleton}
//       />

      
//       <skinnedMesh
//         geometry={nodes['Wolf3D_Outfit_Bottom'].geometry}
//         material={materials.Wolf3D_Outfit_Bottom}
//         skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
//         material={materials.Wolf3D_Outfit_Footwear}
//         skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Top.geometry}
//         material={materials.Wolf3D_Outfit_Top}
//         skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
//       />
     
//       <skinnedMesh
//         name="EyeRight"
//         geometry={nodes.EyeRight.geometry}
//         material={nodes.EyeRight.material}
//         skeleton={nodes.EyeRight.skeleton}
//         morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Head"
//         geometry={nodes.Wolf3D_Head.geometry}
//         material={materials.Wolf3D_Skin}
//         skeleton={nodes.Wolf3D_Head.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Teeth"
//         geometry={nodes.Wolf3D_Teeth.geometry}
//         material={materials.Wolf3D_Teeth}
//         skeleton={nodes.Wolf3D_Teeth.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
//       />
//     </group>
//   );
// }

// useGLTF.preload(
//   "https://res.cloudinary.com/dfzxz7xsy/image/upload/v1686924635/GLB%20Folder/test_esqu05.glb"
// );
