/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 shirt.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ShirtModel(props) {
  const { nodes, materials } = useGLTF(props.srcModel)
  return (
    <group {...props} dispose={null} scale={0.01} >
      <mesh castShadow geometry={nodes.Component_Shirt.geometry} material={materials['Wolf3D_Outfit_Top.001']}  />
    </group>
  )
}

